export const allProducts = [
  {
    id: 1,
    title: "App Exc 1pc Ayam + Nasi",
    alt: "App Exc 1pc Ayam + Nasi",
    category: "BK App Exclusive",
    desc: "1pc Ayam + Nasi",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/11/7/rzap8tqfy9rdkntskcfpdh_product_details.jpg",
    priceNow: "Rp.15,455",
    priceThen: "28,636",
    slug: "appExclusive/appExclusive1ayam",
  },
  {
    id: 2,
    title: "Paket Cheese Whopper® JR Regular",
    alt: "Paket Cheese Whopper® JR Regular",
    category: "BK App Exclusive",
    desc: "Cheese Whopper® JR + Fries Regular + Coke Regular",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/11/7/zawowefhsqwdcxry5k3k48_product_details.jpg",
    priceNow: "Rp.25,000",
    priceThen: "49,545",
    slug: "appExclusive/appExclusivepaketCheese",
  },
  {
    id: 3,
    title: "App Exc BBQ Beef Rasher",
    alt: "App Exc BBQ Beef Rasher",
    category: "BK App Exclusive",
    desc: "",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/3/20/9xl3ak2puc6xgzx3teshaa_product_details.jpg",
    priceNow: "Rp.23,182",
    priceThen: "35,909",
    slug: "appExclusive/appExclusivebbqRasher",
  },
  {
    id: 4,
    title: "8 Pcs Ayam",
    alt: "8 Pcs Ayam",
    category: "BK App Exclusive",
    desc: "",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/3/20/trqkoqzxm32tkxjvpsw2he_product_list.jpg",
    priceNow: "Rp.100,000",
    priceThen: "145,455",
    slug: "appExclusive/appExclusive8ayam",
  },
  {
    id: 5,
    title: "BOGO Paket BESAR 1",
    alt: "BOGO Paket BESAR 1",
    category: "BK App Exclusive",
    desc: "2 Pcs Ayam Besar + 2 Nasi + 2 Jasmine Tea ukuran Medium. Resep Ayam Lebih Renyah dan Gurih.  ",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/3/20/trqkoqzxm32tkxjvpsw2he_product_list.jpg",
    priceNow: "Rp. 54,545",
    priceThen: "71,818",
    slug: "appExclusive/appExclusivebogo",
  },
  {
    id: 6,
    title: "Blitz 2 Ayam Crispy",
    alt: "BOGO Paket BESAR 1",
    category: "Promo Hari Ini",
    desc: "2pc Ayam Crispy",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/fqmtrzjpkdbgxgjdxdkgva_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "40,000",
    slug: "promo/promoblitzAyam",
  },
  {
    id: 7,
    title: "Blitz 2 Choco Pie",
    alt: "Blitz 2 Choco Pie",
    category: "Promo Hari Ini",
    desc: "Blitz 2 Choco Pie",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/wcyzes3qgmpbmotsyfbr6j_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "25,454",
    slug: "promo/promoblitzChoco",
  },
  {
    id: 8,
    title: "Blitz 2 Coke Medium",
    alt: "Blitz 2 Coke Medium",
    category: "Promo Hari Ini",
    desc: "Blitz 2 Coke Medium",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/knh4xk6px8s59wiktblrjt_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "33,636",
    slug: "promo/promoblitzCoke",
  },
  {
    id: 9,
    title: "Blitz 2 Fries Medium",
    alt: "Blitz 2 Fries Medium",
    category: "Promo Hari Ini",
    desc: "Blitz 2 Fries Medium",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/kkpxalsvlbgqvevlrncmqi_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "33,636",
    slug: "promo/promoblitzFries",
  },
  {
    id: 10,
    title: "Blitz 2 Jasmine Tea",
    alt: "Blitz 2 Jasmine Tea",
    category: "Promo Hari Ini",
    desc: "Blitz 2 Jasmine Tea",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/mwsrgjdtjtdynps2bp4rqd_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "33,636",
    slug: "promo/promoblitzJasmine",
  },
  {
    id: 11,
    title: "Kejutan Meriah Paket Rame-Rame",
    alt: "Blitz 2 Jasmine Tea",
    category: "NEW! Cheese Dunk [Limited Time Offer]",
    desc: "Blitz 2 Jasmine Tea",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/26/l5hnnrakv76bqwr2vjfeaq_product_list.jpg",
    price: "Rp. 109,091",
    slug: "promo/promopaketMeriah",
  },
  {
    id: 12,
    title: "King Box Cheese Whopper® Cheese Dunk",
    alt: "King Box Cheese Whopper® Cheese Dunk",
    category: "NEW! Cheese Dunk [Limited Time Offer]",
    desc: "King Box Cheese Whopper® Jr Cheese Dunk",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/21/ixn3b5jmjxdtmfxbaydtwu_product_list.jpg",
    price: "Rp. 90,909",
    slug: "cheesedunk/cheesedunkkingBox",
  },
  {
    id: 13,
    title: "King Box Cheese Whopper® Jr Cheese Dunk",
    alt: "King Box Cheese Whopper® Jr Cheese Dunk",
    category: "NEW! Cheese Dunk [Limited Time Offer]",
    desc: "King Box Cheese Whopper® Jr Cheese Dunk",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/21/ixn3b5jmjxdtmfxbaydtwu_product_list.jpg",
    price: "Rp. 76,364",
    slug: "cheesedunk/cheesedunkkingBoxJr",
  },
  {
    id: 14,
    title: "Paket Cheese Whopper® Cheese Dunk",
    alt: "King Box Cheese Whopper® Jr Cheese Dunk",
    category: "NEW! Cheese Dunk [Limited Time Offer]",
    desc: "King Box Cheese Whopper® Jr Cheese Dunk",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/21/yehwmkgua5nhzyhmzyfgxg_product_list.jpg",
    price: "Rp. 79,545",
    slug: "cheesedunk/cheesedunkcheeseWhopper",
  },
  {
    id: 15,
    title: "Paket Cheese Whopper® Jr Cheese Dunk",
    alt: "King Box Cheese Whopper® Jr Cheese Dunk",
    category: "NEW! Cheese Dunk [Limited Time Offer]",
    desc: "King Box Cheese Whopper® Jr Cheese Dunk",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/21/yehwmkgua5nhzyhmzyfgxg_product_list.jpg",
    price: "Rp. 65,000",
    slug: "cheesedunk/cheesedunkcheeseWhopperJr",
  },
  {
    id: 16,
    title: "NEW! King Fusion Nutella® [Limited Time Offer]",
    alt: "NEW! King Fusion Nutella® [Limited Time Offer]",
    category: "NEW! King Fusion Nutella® [Limited Time Offer]",
    desc: "King Fusion Nutella®",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/20/dawjp7wtzvta5smwtahzvx_product_list.jpg",
    price: "Rp. 16,818",
    slug: "",
  },
  {
    id: 17,
    title: "King Box Mexican Whopper® Medium",
    alt: "King Box Mexican Whopper® Medium",
    category: "Heinz® Mexican Whopper",
    desc: "King Fusion Nutella®",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/10/19/k2djuj3u7xhfraukcjgfwo_product_list.jpg",
    price: "Rp. 90,909",
    slug: "",
  },
  {
    id: 18,
    title: "King Box Mexican Whopper® Jr Medium",
    alt: "King Box Mexican Whopper® Jr Medium",
    category: "Heinz® Mexican Whopper",
    desc: "King Box Mexican Whopper®",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/10/19/k2djuj3u7xhfraukcjgfwo_product_list.jpg",
    price: "Rp. 71,819",
    slug: "",
  },
  {
    id: 19,
    title: "Paket Mexican Whopper® Medium",
    alt: "King Box Mexican Whopper® Jr Medium",
    category: "Heinz® Mexican Whopper",
    desc: "Paket Mexican Whopper®",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/10/19/g5q9ufxfpg8uvxsmgdkmnb_product_list.jpg",
    price: "Rp. 79,545",
    slug: "",
  },
  {
    id: 20,
    title: "Paket Mexican Whopper® Jr Medium",
    alt: "King Box Mexican Whopper® Jr Medium",
    category: "Heinz® Mexican Whopper",
    desc: "Paket Mexican Whopper®",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/11/27/kzq9my5uwwgcvazua4ltb5_product_list.jpg",
    price: "Rp. 60,455",
    slug: "",
  },
  {
    id: 21,
    title: "King Box Cheese Lava Angus Burger",
    alt: "King Box Mexican Whopper® Jr Medium",
    category: "Gold Collection",
    desc: "Gold Collection",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/13/hjhkcb28usc7xjufxsqnea_product_list.jpg",
    price: "Rp. 76,364",
    slug: "",
  },
  {
    id: 22,
    title: "King Box BBQ Angus Burger",
    alt: "King Box Mexican Whopper® Jr Medium",
    category: "Gold Collection",
    desc: "Gold Collection",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/13/hjhkcb28usc7xjufxsqnea_product_list.jpg",
    price: "Rp. 76,364",
    slug: "",
  },
  {
    id: 23,
    title: "Paket Cheese Lava Angus Burger",
    alt: "King Box Mexican Whopper® Jr Medium",
    category: "Gold Collection",
    desc: "Gold Collection",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/13/6ksicnaz2knjaiekspmljp_product_list.jpg",
    price: "Rp.65,000",
    slug: "",
  },
  {
    id: 24,
    title: "Paket BBQ Angus Burger",
    alt: "King Box Mexican Whopper® Jr Medium",
    category: "Gold Collection",
    desc: "Gold Collection",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/13/hjhkcb28usc7xjufxsqnea_product_list.jpg",
    price: "Rp.65,000",
    slug: "",
  },
];
