export const allProducts = [
  {
    id: 1,
    title: "App Exc 1pc Ayam + Nasi",
    alt: "App Exc 1pc Ayam + Nasi",
    category: "app",
    desc: "1pc Ayam + Nasi",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/11/7/rzap8tqfy9rdkntskcfpdh_product_details.jpg",
    priceNow: "Rp.15,455",
    priceThen: "28,636",
  },
  {
    id: 2,
    title: "Paket Cheese Whopper® JR Regular",
    alt: "Paket Cheese Whopper® JR Regular",
    category: "app",
    desc: "Cheese Whopper® JR + Fries Regular + Coke Regular",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/11/7/zawowefhsqwdcxry5k3k48_product_details.jpg",
    priceNow: "Rp.25,000",
    priceThen: "49,545",
  },
  {
    id: 3,
    title: "App Exc BBQ Beef Rasher",
    alt: "App Exc BBQ Beef Rasher",
    category: "app",
    desc: "",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/3/20/9xl3ak2puc6xgzx3teshaa_product_details.jpg",
    priceNow: "Rp.23,182",
    priceThen: "35,909",
  },
  {
    id: 4,
    title: "8 Pcs Ayam",
    alt: "8 Pcs Ayam",
    category: "app",
    desc: "",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/3/20/trqkoqzxm32tkxjvpsw2he_product_list.jpg",
    priceNow: "Rp.100,000",
    priceThen: "145,455",
  },
  {
    id: 5,
    title: "BOGO Paket BESAR 1",
    alt: "BOGO Paket BESAR 1",
    category: "app",
    desc: "2 Pcs Ayam Besar + 2 Nasi + 2 Jasmine Tea ukuran Medium. Resep Ayam Lebih Renyah dan Gurih.  ",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/3/20/trqkoqzxm32tkxjvpsw2he_product_list.jpg",
    priceNow: "Rp. 54,545",
    priceThen: "71,818",
  },
  {
    id: 6,
    title: "Blitz 2 Ayam Crispy",
    alt: "BOGO Paket BESAR 1",
    category: "promo",
    desc: "2pc Ayam Crispy",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/fqmtrzjpkdbgxgjdxdkgva_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "40,000",
  },
  {
    id: 7,
    title: "Blitz 2 Choco Pie",
    alt: "Blitz 2 Choco Pie",
    category: "promo",
    desc: "Blitz 2 Choco Pie",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/wcyzes3qgmpbmotsyfbr6j_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "25,454",
  },
  {
    id: 8,
    title: "Blitz 2 Coke Medium",
    alt: "Blitz 2 Coke Medium",
    category: "promo",
    desc: "Blitz 2 Coke Medium",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/knh4xk6px8s59wiktblrjt_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "33,636",
  },
  {
    id: 9,
    title: "Blitz 2 Fries Medium",
    alt: "Blitz 2 Fries Medium",
    category: "promo",
    desc: "Blitz 2 Fries Medium",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/kkpxalsvlbgqvevlrncmqi_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "33,636",
  },
  {
    id: 10,
    title: "Blitz 2 Jasmine Tea",
    alt: "Blitz 2 Jasmine Tea",
    category: "promo",
    desc: "Blitz 2 Jasmine Tea",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/1/mwsrgjdtjtdynps2bp4rqd_product_list.jpg",
    priceNow: "Rp. 21,818",
    priceThen: "33,636",
  },
  {
    id: 11,
    title: "Kejutan Meriah Paket Rame-Rame",
    alt: "Blitz 2 Jasmine Tea",
    category: "new",
    desc: "Blitz 2 Jasmine Tea",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/26/l5hnnrakv76bqwr2vjfeaq_product_list.jpg",
    price: "Rp. 109,091",
  },
  {
    id: 12,
    title: "King Box Cheese Whopper® Cheese Dunk",
    alt: "King Box Cheese Whopper® Cheese Dunk",
    category: "new",
    desc: "King Box Cheese Whopper® Jr Cheese Dunk",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/21/ixn3b5jmjxdtmfxbaydtwu_product_list.jpg",
    price: "Rp. 90,909",
  },
  {
    id: 13,
    title: "King Box Cheese Whopper® Jr Cheese Dunk",
    alt: "King Box Cheese Whopper® Jr Cheese Dunk",
    category: "new",
    desc: "King Box Cheese Whopper® Jr Cheese Dunk",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/21/ixn3b5jmjxdtmfxbaydtwu_product_list.jpg",
    price: "Rp. 76,364",
  },
  {
    id: 14,
    title: "Paket Cheese Whopper® Cheese Dunk",
    alt: "King Box Cheese Whopper® Jr Cheese Dunk",
    category: "new",
    desc: "King Box Cheese Whopper® Jr Cheese Dunk",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/21/yehwmkgua5nhzyhmzyfgxg_product_list.jpg",
    price: "Rp. 79,545",
  },
  {
    id: 15,
    title: "Paket Cheese Whopper® Jr Cheese Dunk",
    alt: "King Box Cheese Whopper® Jr Cheese Dunk",
    category: "new",
    desc: "King Box Cheese Whopper® Jr Cheese Dunk",
    img: "https://media-order.bkdelivery.co.id/thumb/product_photo/2023/12/21/yehwmkgua5nhzyhmzyfgxg_product_list.jpg",
    price: "Rp. 65,000",
  },
];
