export const homeMenus = [
  {
    id: 1,
    img: "https://media-order.bkdelivery.co.id/thumb/group_photo/2023/3/15/znilxvdnwuyurvfmej3lft_product_list.jpg",
    // img: "../assets/images/menus/menu1.jpg",
    title: "BK APP EXCLUSIVE",
    link: "/product",
    alt: "bk app exclusive",
  },
  {
    id: 2,
    title: "Promo Hari Ini",
    link: "/product",
  },
  {
    id: 3,
    title: "NEW! Cheese Dunk [Limited Time Offer]",
    link: "/product",
  },
  {
    id: 4,
    title: "NEW! King Fusion Nutella® [Limited Time Offer]",
    link: "/product",
  },
  {
    id: 5,
    title: "Heinz® Mexican Whopper",
    img: "https://media-order.bkdelivery.co.id/thumb/group_photo/2023/10/23/hennaxjqiyceh79jnxto4k_product_list.jpg",
    alt: "Heinz Mexican Whopper",
    link: "/product",
  },
  {
    id: 6,
    title: "Gold Collection",
    link: "/product",
  },
  {
    id: 7,
    title: "Cheese Whopper®",
    img: "https://media-order.bkdelivery.co.id/thumb/group_photo/2023/11/2/fwvutetzjew4arsjqzq9td_product_list.jpg",
    alt: "Heinz Mexican Whopper",
    link: "/product",
  },
  {
    id: 8,
    title: "Cheeseburger Favorite",
    img: "https://media-order.bkdelivery.co.id/thumb/group_photo/2023/11/2/ahjlc47bb9hstuc3cc9en2_product_list.jpg",
    alt: "Heinz Mexican Whopper",
    link: "/product",
  },
  {
    id: 9,
    title: "King's Chicken Rasa Baru",
    img: "https://media-order.bkdelivery.co.id/thumb/group_photo/2023/6/3/bzilpvmecz3gmmngfan9vg_product_list.jpg",
    alt: "Heinz Mexican Whopper",
    link: "/product",
  },
  {
    id: 10,
    title: "Kids Meal",
    img: "https://media-order.bkdelivery.co.id/thumb/group_photo/2023/3/15/syhbxldehjxkumhbs5yiz9_product_list.jpg",
    alt: "Heinz Mexican Whopper",
    link: "/product",
  },
  {
    id: 11,
    title: "Side & Dessert",
    img: "https://media-order.bkdelivery.co.id/thumb/group_photo/2023/10/10/fkj8wesyvwhxvwfs4um9mt_product_list.jpg",
    alt: "Heinz Mexican Whopper",
    link: "/product",
  },
  {
    id: 12,
    title: "Kings Deals",
    img: "https://media-order.bkdelivery.co.id/thumb/group_photo/2023/3/15/5s3jdve3uve4itsndqnqkm_product_list.jpg",
    alt: "Heinz Mexican Whopper",
    link: "/product",
  },
];
